name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub

        run: echo "300690dhgr" | docker login -u "dariana.gomez@uc.cl" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t darigo/angular-bef:version1 .
          docker push darigo/angular-bef:version1
