name: Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'  

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli  # Instala Angular CLI globalmente

      - name: Build Angular app
        run: npm run build -- --configuration=demo  # Construye usando el entorno demo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "300690dhgr" | docker login -u "dariana.gomez@uc.cl" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t darigo/angular-bef:version1 .
          docker push darigo/angular-bef:version1

